version: "3.8"

services:
  spa:
    build:
      context: .
      dockerfile: Dockerfile.spa
    ports:
      - "5001:5001"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CHAT_SERVICE_URL=${CHAT_SERVICE_URL}
      - SECRET_KEY=${SECRET_KEY}

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    expose:
      - "5002"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_XUNFEI1_API_KEY=${CLIENT_XUNFEI1_API_KEY}
      - CLIENT_XUNFEI2_API_KEY=${CLIENT_XUNFEI2_API_KEY}
      - CLIENT_XUNFEI_BASE_URL=${CLIENT_XUNFEI_BASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    deploy:
      replicas: 2  # 根据需要调整实例数量

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - chat
