version: "3.8"

services:
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CHAT_SERVICE_URL1=http://chat:5002
      - CHAT_SERVICE_URL2=http://chat:5002
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5001:5001" 
    networks:
      - backend

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_XUNFEI_API_KEY=${CLIENT_XUNFEI_API_KEY}
      - CLIENT_XUNFEI_BASE_URL=${CLIENT_XUNFEI_BASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - backend
    ports:
      - "5002:5002"

networks:
  backend:
    driver: bridge
