name: CI/CD Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black

      - name: Auto format code with Black
        run: |
          black .
          git diff

      - name: Commit formatted code if needed
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: 'Automatically format code with Black'
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Chat dependencies
        run: pip install -r chat/requirements.txt

      - name: Install SPA dependencies
        run: pip install -r spa/requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run Chat tests
        working-directory: ./chat
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/chat  # 关键！同时包含根目录和 chat 目录
        run: pytest tests/ -v

      - name: Run SPA tests
        working-directory: ./spa
        run: pytest tests/ -v